let gameBoard;
/* generated by deepseek */
let possibilities = [
    // Horizontal wins
    "111000000",  // top row
    "000111000",  // middle row
    "000000111",  // bottom row
    
    // Vertical wins
    "100100100",  // left column
    "010010010",  // middle column
    "001001001",  // right column
    
    // Diagonal wins
    "100010001",  // main diagonal (top-left to bottom-right)
    "001010100"   // anti-diagonal (top-right to bottom-left)
];
/* end of ai generated content */
function initializeGame(){
    gameBoard = [["-","-","-"],["-","-","-"],["-","-","-"]];
    
}
function showGameBoard(){
        for(let row=0;row<gameBoard.length;row++){
            for(let col=0;col<gameBoard.length;col++){
                console.log(gameBoard[row][col]);
            }
        }
}

function mark(marker, row, col){
    if(marker!=0 && marker!=1){
        console.log("Unknown marker type");
        return;
    }
    if(marker == 1){
        marker = "X";
    }
    else{
        marker = "O";
    }
    gameBoard[row][col] = marker;
    showGameBoard(gameBoard,marker);
    checkWinner(gameBoard, marker);
}

function EncodeGrid(gameBoard, marker){
        let code=""; 
        for(let row=0;row<gameBoard.length;row++){
            for(let col=0;col<gameBoard.length;col++){
                if(gameBoard[row][col] == marker){
                        code+=1;
                }
                else{
                    code +=0;
                }
            }
        }
        return code;
}
function checkWinner(gameBoard,marker){
    let currentState = EncodeGrid(gameBoard,marker);
    possibilities.forEach((state)=>{
        if(currentState == state){
            console.log("winner is "+ marker);
            initializeGame();
            return;
        }            
    });

}

initializeGame();
